# Baikal Summer School

### Arsenii Gavrikov, ВШЭ + ОИЯИ
### gavrikov@jinr.ru

# Часть №1. Python и базовые библиотеки

## Общая информация о языке

**Особенности**:  
- интерпретируемый
- объектно-ориентированный
- высокоуровневый язык
- встроенные высокоуровневые структуры данных
- динамическая типизация
- синтаксис прост в изучении
- поддержка модулей и пакетов (большинство библиотек
бесплатны)
- универсальный
- интеграция с другими языками (C (Cython), C++, Java (JPython))  

**Стиль оформления кода** - **PEP8**.  

*Самое главное из PEP8:*  
- отступ – 4 пробела
- длина строки < 80 символов
- переменные: var_recommended
- константы: CONST_RECOMMENDED

### Типы

**Все типы данных** в Python относятся к одной из **2-х категорий**: **изменяемые (mutable)** и **неизменяемые (immutable)**.   

*Неизменяемые объекты*:  
* числовые данные (int, float), 
* bool,
* None,
* символьные строки (class 'str'), 
* кортежи (tuple).  

*Изменяемые объекты*:  
* списки (list), 
* множества (set), 
* словари (dict).  

Вновь определяемые пользователем типы (классы) могут быть определены как неизменяемые или изменяемые. Изменяемость объектов определённого типа является принципиально важной характеристикой, определяющей, может ли объект такого типа **выступать в качестве ключа для словарей (dict)** или нет.

### input, output (print)

Вывод, ввод данных

In [1]:
x = int(input("Сколько Вам лет? "))
y = 12
print('Вам ', x * y, 'месяцев')

Сколько Вам лет? 16
Вам  192 месяцев


### int

**Целочисленный тип переменной в питоне**

Чтобы задать переменную, не нужно указывать ее тип -- достаточно присвоить ей значение. При этом тип определится автоматически.

Давайте попробуем завести переменную, присвоить ей значение -- целое число, и вывести на экран ее значение и тип (type):

In [2]:
x = 5

print(x, '|', type(x))

5 | <class 'int'>


Как видно, тип получившейся переменной -- int.

C int'овыми переменными можно производить стандартные матеатические операции -- сложение, вычитание, умножение, деление, возведение в степень, взятие остатка при делении на число

Деление переменных типа int бывает двух типов -- целочисленное (с помощью символа //) и нецелочисленное (символ /). Результатом первого типа деления будет целое число, второго -- дробное. 

In [3]:
a = 4 + 5
b = 4 * 5
c = 5 // 4
d = 5 / 4
e = 5**4 # 5 в степени 4
f = 5%4 # остаток при делении 5 на 4

print(a, b, c, d, e)
print(e)

9 20 1 1.25 625
625


### float

**Тип переменной для хранения дробных чисел в питоне**:

In [4]:
y = 12.345

print(y, '|', type(y))

12.345 | <class 'float'>


In [5]:
a = 4.2 + 5.1
b = round(4.2 * 5.1, 2)
c = 5.0 / 4.0
d = 5.25 // 4.25
e = 5.25 ** 4.0

print(a, b, c, d, e)

9.3 21.42 1.25 1.0 759.69140625


Переменную типа int можно привести к типу float 

In [6]:
a = 5
print(a, '|', type(a))
a = float(a)
print(a, '|', type(a))

5 | <class 'int'>
5.0 | <class 'float'>


### bool

In [7]:
a = True
b = False

print(a, '|', type(a))

print(b, '|', type(b))

True | <class 'bool'>
False | <class 'bool'>


У типа bool существует связь с типом int -- переменная со значением True соответствует int'овой переменной со значением 1, а переменная со значением False -- int'овой переменной со значением 0.

Давайте в этом убедимся, попробовав сложить значения переменных a и b:

In [8]:
print(a + b)
print(a + a)
print(b + b)

1
2
0


Логические "и", "или", "не" в питоне обозначаюся ключевыми словами `and`, `or`, `not` соответственно:

In [9]:
print(True and False)
print(True or True)
print(not False)

False
True
True


### str

**строка**

In [1]:
'ОИ' + 'Я' + 'И'*3

'ОИЯИИИ'

Тип переменной "строка". Нужен для хранения и выполнения операций с строками -- наборами символов. В питоне строку можно задавать как с помощью одинарных кавычек, так и с помощью двойных, разницы нет (главное, чтобы в начале и конце одной строки стояли одинаковые кавычки):

In [11]:
x = "abc"
y = 'xyz'
print(x, '|', type(x))
print(y, '|', type(y))

abc | <class 'str'>
xyz | <class 'str'>


### Структуры данных

### list, tuple, set, dict

Это типы данных, которые являются хранилищами для других типов данных.

`list` (массив, список, лист). Это контейнер, куда можно положить сколько угодно других переменных, значений, и эти переменные даже могут быть разных типов и даже так же могут быть контейнерами! То есть, в list можно положить list:

Чтобы задать list, надо в квадратные скобки `[]` положить нужные элементы. Пустые скобки задают пустой list. Пустой лист также можно задать, написав `list()`:

In [12]:
a = list()
b = []

# убедимся, что два варианта создания пустого массива эквивалентны:
print(a == b)

True


In [13]:
c = [2, 'a', [4, 'stroka', 6.56]]
c

[2, 'a', [4, 'stroka', 6.56]]

### tuple

**кортеж**

этот тип данных очень похож на list, имеет ту же структуру, но отличается тем, что он неизменяемый

это нужно, например, чтобы `tuple` мог выступать в качестве ключей словаря (о них ниже). list в качестве ключей словаря выступать не может.

Задать tuple можно круглыми скобками:

In [14]:
t = ('a', 5, 12.345, (2, 'b'))
t

('a', 5, 12.345, (2, 'b'))

Tuple нельзя изменять. Давайте в этом убедимся:


In [15]:
t.append(5)

AttributeError: 'tuple' object has no attribute 'append'

In [16]:
t[0] = 9

TypeError: 'tuple' object does not support item assignment

### set

**Множество**

Множество -- это массив, в котором элементы не могут повторяться (то есть, как и в математическом определении множества)

Внутри языка множество устроено совсем не так, как массив или кортеж, элементы множества хранятся не последовательно, поэтому к элементам множества нельзя обрашаться по индексу.

Пустое множество можно создать с помощью set():

In [17]:
s = set()

print(s, '|', type(s))

set() | <class 'set'>


In [18]:
s = set([5, 2, 3, 2])
s

{2, 3, 5}

### dict

**словарь, ассоциативный массив**

Словарь -- это структура данных, которая представляет отображение из одного типа данных в другой. Представляет собой набор пар ключ-значение, в качестве ключа могут выступать immutable типы данных (int, str, tuple, ...)

Массивы, которые мы до этого рассматривали, были отображением непрерывного отрезка [0, n] в другой тип данных. `dict` может быть гораздо удобнее, когда нужно использовать в качестве ключа другой тип данных (например, сопоставить именам людей (str) их даты рождения) или когда в качестве ключа хочется использовать int, но не все значения из промежутка [0, n] нужны.

Пустой словарь можно создать либо с помощью `{}`, либо с `dict()`:

In [19]:
d = {}
dd = dict()

print(d == dd, '|', type(d))

True | <class 'dict'>


In [20]:
key = 2
value = 100

d[key] = value
d

{2: 100}

**Условный оператор if**

В коде часто приходится проверять выполнимость или невыполнимость каких-то условий. Синтаксис следующий

```
if <условие1 (булевское выражение)> :
    <код, который выполнится, если условие верно>
elif <условие2 (булевское выражение)>:
    <код, который выполнится, если условие1 было неверно, а условие2 верно>
else:
    <код, который выполнится, если условие1 и условие2 были неверны>
```

Обратите внимание, что код, который должен выполняться внутри каждого условия, записывается с отступом в 4 пробела от уровня if, elif и else: в питоне области видимости переменных обозначаются отступами.

*То есть, отступы позволяют понять, где начинается код, который должен выполняться при выполнении условия в if, и где заканчивается*

Пример конструкции:

In [21]:
x = 3
y = 5
if (x >= 3) and (y > 2):
    print("x больше 3 и y больше 2")
elif (x >= 3) and (y < 2):
    print("x больше 3 и y меньше 2")
else:
    print("x меньше 3")

x больше 3 и y больше 2


### Циклы - for и while

iterable стректуры данных так называются, потому что по ним можно *итерироваться* -- последовательно получать значения последовательных элементов этой структуры данных. Итерироваться можно с помощью циклов `for` или `while`.

Синтаксис следующий:

```
for element in iterable:
    <code>
```

здесь каждую новую итерацию цикла в element будет записываться очередное значение из контейнера iterable и с ним можно будет работать внутри тела цикла (`code`). Когда код внутри тела цикла отработает, начнется новая итерация цикла -- в переменную element запишется следующее значение из iterable и опять будет выполняться code.

Код, который будет выполняться каждую итерацию цикла, записывается после двоеточия с отступом 4 пробела от строчки c `for`.

Посмотрим на примере:

In [22]:
# создадим list элементов
models = ['decision tree', 'linear model', 'svm', 'ensemble']

# итерируемся по названиям модели: каждую итерацию цикла в переменную model будет
# записываться новое значение из models и оно будет использоваться для print(model)
for model in models:
    # тело цикла. Здесь с отступом в 4 пробела нужно описать код, который будет выполняться на каждой итерации цикла.
    print(model)
    
# этот код уже будет выполняться ПОСЛЕ цикла, потому что он записан без отступа в 4 пробела после for:
print("Done")

decision tree
linear model
svm
ensemble
Done


Синтаксис `while`:

```
while <условие (булевское выражение)>:
    <code>
```

Здесь код, написанный вместо `code` будет выполняться каждую итерацию цикла, пока условие после `while` будет выполняться.

Посмотрим на примере: Напишем цикл, в котором будем выводить переменную x и увеличивать x на 1, пока x не станет больше 10:

In [23]:
while x <= 10:
    # более удобный способ записи x = x + 1
    x += 1

### modules

**Модули** - это "библиотеки" Python. То есть это самостоятельные, объединённые технически и логически, именованные части Python кода

Можно рассматривать их как код, функции, записанные в других файлах (модулях), и чтобы использовать их в своем коде, нужно подключить эти файлы (модули)

In [24]:
import collections

In [25]:
# импортируем структуру данных Counter из библиотеки collections
from collections import Counter

* Импортировать с другим именем (чаще всего используется для локаничности кода):

In [26]:
import collections as col

In [27]:
count = col.Counter()

Жизненный пример:

In [28]:
import numpy as np
import pandas as pd

# Numpy

In [29]:
import numpy as np

Воспоминания о работе с массивами numpy

In [30]:
x = np.array([1,2,3,5,8], dtype=np.float32)
print(x)
print(x.shape)

[1. 2. 3. 5. 8.]
(5,)


In [31]:
x = np.array([1,2,3,5,8], dtype=np.int8)
print(x)
print(x.shape)

[1 2 3 5 8]
(5,)


In [32]:
x = np.array([[0,-1],[1,0]], dtype=np.float32)
print(x)
print(x.shape)

[[ 0. -1.]
 [ 1.  0.]]
(2, 2)


In [33]:
x = np.array([[0,-1],[1,0]], dtype=np.float32)
z = np.array([1.0,0], dtype=np.float32)
print(x @ z)
print(x.dot(z))

[0. 1.]
[0. 1.]


In [34]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
x = np.arange(10, -1, -1)
print(x)

[10  9  8  7  6  5  4  3  2  1  0]


In [36]:
x = np.linspace(0, 2, 7)
print(x)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.        ]


In [37]:
z = np.zeros((3, 2), dtype=np.float32)
print(z, '\n')

o = np.ones((3, 2), dtype=np.float32)
print(o, '\n')

t = np.full(z.shape, 5, dtype=np.float32)
print(t, '\n')

[[0. 0.]
 [0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[5. 5.]
 [5. 5.]
 [5. 5.]] 



In [38]:
x = np.arange(24)
print(x)
print(x.shape)
print()

x = x.reshape(4,6)
print(x)
print(x.shape)
print()

x = x.reshape(2,3,4)
print(x)
print(x.shape)
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)



In [39]:
x = np.arange(5)
print(x)
print(x.shape)
print()

x = x.reshape(5,1)
print(x)
print(x.shape)
print()

x = x.reshape(1,5)
print(x)
print(x.shape)
print()

[0 1 2 3 4]
(5,)

[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)

[[0 1 2 3 4]]
(1, 5)



# Срезы

In [40]:
x = np.arange(16)
print(x)
print()
print("1.  x[1]        = {}".format(x[1]))
print("2.  x[-2]       = {}".format(x[-2]))
print("3.  x[2:9]      = {}".format(x[2:9]))
print("4.  x[:9]       = {}".format(x[:9]))
print("5.  x[2:]       = {}".format(x[2:]))
print("6.  x[:]        = {}".format(x[:]))
print("7.  x[2:9:3]    = {}".format(x[2:9:3]))
print("8.  x[9:2:-1]   = {}".format(x[9:2:-1]))
print("9.  x[::-1]     = {}".format(x[::-1]))
print("10. x[:-1]      = {}".format(x[:-1]))
print("11. x[-9:-2]    = {}".format(x[-9:-2]))
print("12. x[-9:-2:2]  = {}".format(x[-9:-2:2]))
print("13. x[-2:-9:-1] = {}".format(x[-2:-9:-1]))
print("14. x[-2:-9:-2] = {}".format(x[-2:-9:-2]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

1.  x[1]        = 1
2.  x[-2]       = 14
3.  x[2:9]      = [2 3 4 5 6 7 8]
4.  x[:9]       = [0 1 2 3 4 5 6 7 8]
5.  x[2:]       = [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15]
6.  x[:]        = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
7.  x[2:9:3]    = [2 5 8]
8.  x[9:2:-1]   = [9 8 7 6 5 4 3]
9.  x[::-1]     = [15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
10. x[:-1]      = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
11. x[-9:-2]    = [ 7  8  9 10 11 12 13]
12. x[-9:-2:2]  = [ 7  9 11 13]
13. x[-2:-9:-1] = [14 13 12 11 10  9  8]
14. x[-2:-9:-2] = [14 12 10  8]


In [41]:
x = np.arange(24)
x = x.reshape(2,3,4)
print(x)
print()
print("1. x[1] =\n{}".format(x[1]))
print("2. x[1,:,:] =\n{}".format(x[1,:,:]))
print("3. x[:,1,:] =\n{}".format(x[:,1,:]))
print("4. x[:,1] =\n{}".format(x[:,1]))
print("5. x[:,:,1] =\n{}".format(x[:,:,1]))
print("6. x[:,:2,:] =\n{}".format(x[:,:2,:]))
print("7. x[:,:,::-1] =\n{}".format(x[:,:,::-1]))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

1. x[1] =
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2. x[1,:,:] =
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
3. x[:,1,:] =
[[ 4  5  6  7]
 [16 17 18 19]]
4. x[:,1] =
[[ 4  5  6  7]
 [16 17 18 19]]
5. x[:,:,1] =
[[ 1  5  9]
 [13 17 21]]
6. x[:,:2,:] =
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[12 13 14 15]
  [16 17 18 19]]]
7. x[:,:,::-1] =
[[[ 3  2  1  0]
  [ 7  6  5  4]
  [11 10  9  8]]

 [[15 14 13 12]
  [19 18 17 16]
  [23 22 21 20]]]


Pandas

In [3]:
import pandas as pd

pd.read_csv("data/telescope_data.csv")

Unnamed: 0   fLength    fWidth   fSize   fConc  fConc1     fAsym  \
0               0   28.7967   16.0021  2.6449  0.3918  0.1982   27.7004   
1               1   31.6036   11.7235  2.5185  0.5303  0.3773   26.2722   
2               2  162.0520  136.0310  4.0612  0.0374  0.0187  116.7410   
3               3   23.8172    9.5728  2.3385  0.6147  0.3922   27.2107   
4               4   75.1362   30.9205  3.1611  0.3168  0.1832   -5.5277   
...           ...       ...       ...     ...     ...     ...       ...   
19015       19015   21.3846   10.9170  2.6161  0.5857  0.3934   15.2618   
19016       19016   28.9452    6.7020  2.2672  0.5351  0.2784   37.0816   
19017       19017   75.4455   47.5305  3.4483  0.1417  0.0549   -9.3561   
19018       19018  120.5135   76.9018  3.9939  0.0944  0.0683    5.8043   
19019       19019  187.1814   53.0014  3.2093  0.2876  0.1539 -167.3125   

        fM3Long  fM3Trans   fAlpha     fDist class  
0       22.0110   -8.2027  40.0920   81.8828     g  
1       23.8238   -9.9574   6.3609  205.2610     g  
2      -64.8580  -45.2160  76.9600  256.7880     g  
3       -6.4633   -7.1513  10.4490  116.7370     g  
4       28.5525   21.8393   4.6480  356.4620     g  
...         ...       ...      ...       ...   ...  
19015   11.5245    2.8766   2.4229  106.8258     h  
19016   13.1853   -2.9632  86.7975  247.4560     h  
19017   41.0562   -9.4662  30.2987  256.5166     h  
19018  -93.5224  -63.8389  84.6874  408.3166     h  
19019 -168.4558   31.4755  52.7310  272.3174     h  

[19020 rows x 12 columns]

DataFrame и Series

In [42]:
# !jupyter nbconvert Part1.ipynb --to slides --post serve --SlidesExporter.reveal_theme=serif  --SlidesExporter.reveal_scroll=True  --SlidesExporter.reveal_transition=none

[NbConvertApp] Converting notebook Sem1.ipynb to slides
[NbConvertApp] Writing 651649 bytes to Sem1.slides.html
[NbConvertApp] Redirecting reveal.js requests to https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.5.0
Traceback (most recent call last):
  File "C:\Users\Ars\anaconda3\Scripts\jupyter-nbconvert-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Ars\anaconda3\lib\site-packages\jupyter_core\application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Ars\anaconda3\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "C:\Users\Ars\anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 346, in start
    self.convert_notebooks()
  File "C:\Users\Ars\anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 518, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Users\Ars\anaconda3\lib\site-packag